In [60]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("heart.csv")

In [61]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [62]:
df = df[["age", "sex", "cp", "trestbps", "chol","fbs","restecg","thalach","thal","target"]]
df = df.rename({"sex": "gender"}, axis=1)
df = df.rename({"cp": "chest_pain"}, axis=1)
df = df.rename({"trestbps": "blood_pressure"}, axis=1)
df = df.rename({"chol": "cholestoral"}, axis=1)
df = df.rename({"fbs": "blood_sugar"}, axis=1)
df = df.rename({"restecg": "resting_electrocardiographic_results"}, axis=1)
df = df.rename({"thalach": "maximum_heart_rate_achieved"}, axis=1)
df = df.rename({"thal": "thalassemia"}, axis=1)
df = df.rename({"target": "heart_disease"}, axis=1)
df.head()

age  gender  chest_pain  blood_pressure  cholestoral  blood_sugar  \
0   52       1           0             125          212            0   
1   53       1           0             140          203            1   
2   70       1           0             145          174            0   
3   61       1           0             148          203            0   
4   62       0           0             138          294            1   

   resting_electrocardiographic_results  maximum_heart_rate_achieved  \
0                                     1                          168   
1                                     0                          155   
2                                     1                          125   
3                                     1                          161   
4                                     1                          106   

   thalassemia  heart_disease  
0            3              0  
1            3              0  
2            3              0  
3            3              0  
4            2              0

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 10 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   age                                   1025 non-null   int64
 1   gender                                1025 non-null   int64
 2   chest_pain                            1025 non-null   int64
 3   blood_pressure                        1025 non-null   int64
 4   cholestoral                           1025 non-null   int64
 5   blood_sugar                           1025 non-null   int64
 6   resting_electrocardiographic_results  1025 non-null   int64
 7   maximum_heart_rate_achieved           1025 non-null   int64
 8   thalassemia                           1025 non-null   int64
 9   heart_disease                         1025 non-null   int64
dtypes: int64(10)
memory usage: 80.2 KB


In [64]:
df = df.dropna()
df.isnull().sum()

age                                     0
gender                                  0
chest_pain                              0
blood_pressure                          0
cholestoral                             0
blood_sugar                             0
resting_electrocardiographic_results    0
maximum_heart_rate_achieved             0
thalassemia                             0
heart_disease                           0
dtype: int64

In [65]:
import pandas as pd
from sklearn.model_selection import train_test_split



# Separate the features and target variable
X = df.drop('heart_disease', axis=1)  # Features
y = df['heart_disease']  # Target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print the shape of the training and testing sets
print("Training set shape:", X_train.shape, y_train.shape)
print("Testing set shape:", X_test.shape, y_test.shape)


Training set shape: (820, 9) (820,)
Testing set shape: (205, 9) (205,)


In [66]:
from sklearn.linear_model import LogisticRegression
l_reg = LogisticRegression()
l_reg.fit(X, y.values)

C:\Users\sana.SANA-L1\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [67]:
y_pred = l_reg.predict(X)

In [68]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))
error

0.45905523340560356

In [69]:
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, y.values)

RandomForestRegressor(random_state=0)

In [70]:
y_pred = random_forest_reg.predict(X)

In [71]:
error = np.sqrt(mean_squared_error(y, y_pred))
error

0.020276142414658475

In [72]:
from sklearn.model_selection import GridSearchCV

max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = RandomForestRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)

GridSearchCV(estimator=RandomForestRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [73]:
regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
error

0.020276142414658475

In [74]:
X

age  gender  chest_pain  blood_pressure  cholestoral  blood_sugar  \
0      52       1           0             125          212            0   
1      53       1           0             140          203            1   
2      70       1           0             145          174            0   
3      61       1           0             148          203            0   
4      62       0           0             138          294            1   
...   ...     ...         ...             ...          ...          ...   
1020   59       1           1             140          221            0   
1021   60       1           0             125          258            0   
1022   47       1           0             110          275            0   
1023   50       0           0             110          254            0   
1024   54       1           0             120          188            0   

      resting_electrocardiographic_results  maximum_heart_rate_achieved  \
0                                        1                          168   
1                                        0                          155   
2                                        1                          125   
3                                        1                          161   
4                                        1                          106   
...                                    ...                          ...   
1020                                     1                          164   
1021                                     0                          141   
1022                                     0                          118   
1023                                     0                          159   
1024                                     1                          113   

      thalassemia  
0               3  
1               3  
2               3  
3               3  
4               2  
...           ...  
1020            2  
1021            3  
1022            2  
1023            2  
1024            3  

[1025 rows x 9 columns]

In [76]:
X = np.array([[71,0,0,112,149,0,1,125,2]])
X

array([[ 71,   0,   0, 112, 149,   0,   1, 125,   2]])

In [84]:
age=df['age']
gender=df['gender']
chest_pain=df['chest_pain']
blood_pressure=df['blood_pressure']
cholestoral=df['cholestoral']
blood_sugar=df['blood_sugar']
resting_electrocardiographic_results=df['resting_electrocardiographic_results']
maximum_heart_rate_achieved=df['maximum_heart_rate_achieved']
thalassemia=df['thalassemia']

In [85]:
y_pred = regressor.predict(X)
y_pred

C:\Users\sana.SANA-L1\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([0.97])

In [86]:
import pickle

In [88]:
data = {"model": regressor,
        "age": age, 
        "gender": gender,
        "chest_pain": chest_pain,
        "blood_pressure": blood_pressure,
        "cholestoral": cholestoral ,
        "blood_sugar": blood_sugar,
        "resting_electrocardiographic_results": resting_electrocardiographic_results,
        "maximum_heart_rate_achieved":maximum_heart_rate_achieved,
        "thalassemia": thalassemia}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [89]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]

In [90]:
age = data["age"]
gender = data["gender"]
chest_pain = data["chest_pain"]
blood_pressure = data["blood_pressure"]
cholestoral = data["cholestoral"]
blood_sugar = data["blood_sugar"]
resting_electrocardiographic_results = data["resting_electrocardiographic_results"]
maximum_heart_rate_achieved = data["maximum_heart_rate_achieved"]
thalassemia = data["thalassemia"]

In [91]:
y_pred = regressor_loaded.predict(X)
y_pred

C:\Users\sana.SANA-L1\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([0.97])